### ISSUE TITLE
x509 error when run k6 gRPC with many VUs

### ISSUE THREAD

**Issue by hojongs** [k6io/k6#1932]
## Environment

- k6 version: `k6 v0.31.1 ((devel), go1.16.2, darwin/amd64)`
- OS and version: macOS Catalina 10.15.5(19F101)
- Docker version and image, if applicable:

### with 1 VU, 300 Iterations
```
          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: k6-grpc.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 300 iterations shared among 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)


running (01m32.9s), 0/1 VUs, 300 complete and 0 interrupted iterations
default ✓ [======================================] 1 VUs  01m32.9s/10m0s  300/300 shared iters

     data_received........: 1.7 MB 18 kB/s
     data_sent............: 250 kB 2.7 kB/s
     grpc_req_duration....: avg=60.58ms  min=40.54ms  med=51ms     max=245.66ms p(90)=87.11ms  p(95)=123.43ms
     iteration_duration...: avg=309.68ms min=201.56ms med=269.63ms max=1.45s    p(90)=403.33ms p(95)=460.14ms
     iterations...........: 300    3.22862/s
     vus..................: 1      min=1 max=1
     vus_max..............: 1      min=1 max=1
```
### with 200 VUs, 300 Iterations
```
          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: k6-grpc.js
     output: -

  scenarios: (100.00%) 1 scenario, 200 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 300 iterations shared among 200 VUs (maxDuration: 10m0s, gracefulStop: 30s)


running (00m01.7s), 000/200 VUs, 300 complete and 0 interrupted iterations
default ✓ [======================================] 200 VUs  00m01.7s/10m0s  300/300 shared iters

     data_received........: 1.7 MB 1.0 MB/s
     data_sent............: 244 kB 144 kB/s
     grpc_req_duration....: avg=74.46ms  min=42.85ms  med=67.09ms  max=777.47ms p(90)=100.79ms p(95)=112.4ms
     iteration_duration...: avg=649.92ms min=274.84ms med=633.07ms max=1.68s    p(90)=1.09s    p(95)=1.19s
     iterations...........: 300    176.920278/s
     vus..................: 79     min=79  max=79
     vus_max..............: 200    min=200 max=200
```

### with 300 VUs, 300 Iterations

```
          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: k6-grpc.js
     output: -

  scenarios: (100.00%) 1 scenario, 300 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 300 iterations shared among 300 VUs (maxDuration: 10m0s, gracefulStop: 30s)

running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0001] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace
ERRO[0002] GoError: x509: certificate signed by unknown authority
running at github.com/loadimpact/k6/js/common.Bind.func1 (native)
default at file:///Users/jeonjongho/IdeaProjects/grpc-star/k6-grpc.js:12:20(7)  executor=shared-iterations scenario=default source=stacktrace

(... I preesed Ctrl-C)

running (00m01.7s), 000/300 VUs, 300 complete and 0 interrupted iterations
default ✓ [======================================] 300 VUs  00m01.6s/10m0s  300/300 shared iters

     data_received........: 1.6 MB 968 kB/s
     data_sent............: 89 kB  54 kB/s
     iteration_duration...: avg=797.32ms min=154.61ms med=613.12ms max=1.64s p(90)=1.39s p(95)=1.44s
     iterations...........: 300    181.424216/s
     vus..................: 130    min=130 max=130
     vus_max..............: 300    min=300 max=300
```

## Steps to Reproduce the Problem

1. Run grpc server with TLS
2. Save k6-grpc.js

```
import grpc from 'k6/net/grpc';
import { check } from 'k6';

const client = new grpc.Client();
client.load(
    [],
    'yourservice.proto'
);

export default () => {
    client.connect('yourservice:31400', {
        plaintext: false
    });

    const data = { name: 'something' };
    const response = client.invoke('YourService/Method', data);
    // check(response, {
    //        'status is OK': (r) => r && r.status === grpc.StatusOK,
    // });
    // console.log(JSON.stringify(response.message));
    client.close();
    // sleep(1);
};
```

3. Run `k6 run -u 300 -i 300 k6-grpc.js`

## Comment

It is weird because it occurs only when I run k6 with more than about 250 VUs.
`-u 100 -i 1000` is fine. but `-u 300 -i 300` causes this error.
Moreover, error message says about certification but I think it's not security error. because it works fine with smaller VUs.

**Comment by hojongs** [comment]
I think so 🤔 Hmm let me try it again to clarify (maybe it will be my infra configuration issue, not k6)

**Comment by hojongs** [comment]
I tried test with local grpc tls server but this API doesn't have cacert param. I mean, `-cacert` parameter in grpcurl or curl.
https://k6.io/docs/javascript-api/k6-net-grpc/client/client-connect-address-params#connectparams

What do you think about adding `cacert` param to grpc Client? @na-- 
I got this output when I call secured gRPC API without cert. (I used self-signed cert)

```
ERRO[0000] GoError: tls: first record does not look like a TLS handshake
        at github.com/loadimpact/k6/js/common.Bind.func1 (native)
        at file:///Users/jeonjongho/IdeaProjects/spring-boot-example/grpc/src/main/resources/cert/k6-grpc.js:12:20(7)  executor=per-vu-iterations scenario=default source=stacktrace
```

**Comment by na--** [comment]
:+1: for adding something like `cacert`. We should also probably respect the already existing [`insecureSkipTLSVerify` option](https://k6.io/docs/using-k6/options#insecure-skip-tls-verify) in the gRPC module. Feel free to open another issue about these!

**Comment by hojongs** [comment]
Thank you for answering fast always!
I added the option you mentioned and ran again `k6 run k6-grpc.js`, But same error occured
```
ERRO[0000] GoError: tls: first record does not look like a TLS handshake
        at github.com/loadimpact/k6/js/common.Bind.func1 (native)
        at file:///Users/jeonjongho/IdeaProjects/spring-boot-example/grpc/src/main/resources/cert/k6-grpc.js:16:20(7)  executor=per-vu-iterations scenario=default source=stacktrace
```
The js file is here.
https://github.com/hojongs/spring-boot-example/blob/grpc-tls/grpc/src/main/resources/cert/k6-grpc.js

But grpcurl worked fine.
grpcurl command option is here.
https://github.com/hojongs/spring-boot-example/blob/grpc-tls/grpc/src/main/resources/cert/grpcurl.sh

`--insecure-skip-tls-verify` command line option for k6 also didn't work.

when I run grpcurl without `-insecure` option, I get this error. It's different from error message from k6 above. So, I guess there is another issue.
```
x509: certificate signed by unknown authority
```

I couldn't get useful log with `-vv` option.
```
DEBU[0000] Starting the REST API server on localhost:6565 
DEBU[0000] Initialization starting...                    component=engine
DEBU[0000] Start of initialization                       executorsCount=1 neededVUs=1 phase=local-execution-scheduler-init
DEBU[0000] Initialized VU #1                             phase=local-execution-scheduler-init
DEBU[0000] Finished initializing needed VUs, start initializing executors...  phase=local-execution-scheduler-init
DEBU[0000] Initialized executor default                  phase=local-execution-scheduler-init
DEBU[0000] Initialization completed                      phase=local-execution-scheduler-init
DEBU[0000] Execution scheduler starting...               component=engine
DEBU[0000] Start of test run                             executorsCount=1 phase=local-execution-scheduler-run
DEBU[0000] Running setup()                               phase=local-execution-scheduler-run
DEBU[0000] Metrics processing started...                 component=engine
DEBU[0000] Starting emission of VU metrics...            component=engine
DEBU[0000] Start all executors...                        phase=local-execution-scheduler-run
DEBU[0000] Starting executor                             executor=default startTime=0s type=per-vu-iterations
DEBU[0000] Starting executor run...                      executor=per-vu-iterations iterations=1 maxDuration=10m0s scenario=default type=per-vu-iterations vus=1
ERRO[0000] GoError: tls: first record does not look like a TLS handshake
        at github.com/loadimpact/k6/js/common.Bind.func1 (native)
        at file:///Users/jeonjongho/IdeaProjects/spring-boot-example/grpc/src/main/resources/cert/k6-grpc.js:16:20(7)  executor=per-vu-iterations scenario=default source=stacktrace
DEBU[0000] Executor finished successfully                executor=default startTime=0s type=per-vu-iterations
DEBU[0000] Regular duration is done, waiting for iterations to gracefully finish  executor=per-vu-iterations gracefulStop=30s scenario=default
DEBU[0000] Running teardown()                            phase=local-execution-scheduler-run
DEBU[0000] Execution scheduler terminated                component=engine error="<nil>"
DEBU[0000] Processing metrics and thresholds after the test run has ended...  component=engine
DEBU[0000] Engine run terminated cleanly                
```

Do you have any idea about this error?

**Comment by na--** [comment]
By this:

> We should also probably respect the already existing insecureSkipTLSVerify option in the gRPC module.

I meant that we don't currently respect that option in the `k6/grpc` module, only in `k6/http` :sweat_smile: That is, we haven't implemented it yet... :disappointed: I invited you to open an issue about it. In any case, when we implement it, it should function similarly to grpcurl's `-insecure` flag.

The `tls: first record does not look like a TLS handshake` error seems to indicate that you're not using TLS with your gRPC server, so maybe try `plaintext: true` in your `connect()` call, e.g. 
```js
    client.connect('localhost:6565', {
        plaintext: true
    });
```

**Comment by hojongs** [comment]
Oh sorry my mistake 😭 Thank you again 🙏

**Comment by hojongs** [comment]
I fixed it, it was my client socket limit problem 😢

**Comment by na--** [comment]
:+1:, just to confirm, this wasn't caused by k6 but rather by your gRPC server?

**Comment by hojongs** [comment]
No. It's from my PC setting.

```sh
$ ulimit -a

...
-n: file descriptors                256
```

Then, my available max connection count < 256

### Solution

```sh
$ ulimit -n 30000
```

After running this command, I can connect to server with connections more than 256.
You can check it with running ghz with --concurrency, --connections options

It's not related with SSL. (just connection limit problem from client environment)
