### ISSUE TITLE
ERRO[0000] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shongcheng** [k6io/k6#1979]
## Environment

- k6 version: k6 v0.31.1 (2021-03-17T13:23:23+0000/e9d8349, go1.15.8, windows/386)
- OS and version: Windows 10 Pro for Workstation, ver 2004, OS Build 19041.928
- Docker version and image, if applicable:

## Expected Behavior

Complete the script without runtime errors.

## Actual Behavior

Gets a "panic: runtime error"

## Steps to Reproduce the Problem

1. Execute the sample script "check.js" from "https://k6.io/docs/using-k6/checks/"
2. Gets the following;
```
  execution: local
     script: scripts/check.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

**ERRO[0000] panic: runtime error: invalid memory address or nil pointer dereference**
goroutine 86 [running]:
runtime/debug.Stack(0x1408f314, 0x1408f324, 0x1408f30c)
        runtime/debug/stack.go:24 +0x83
github.com/loadimpact/k6/js.(*VU).runFn.func1(0x146f1680, 0x1408fda8)
        github.com/loadimpact/k6/js/runner.go:706 +0x165
panic(0xef9be0, 0x1a7fc60)
        runtime/panic.go:969 +0x153
github.com/dop251/goja.AssertFunction.func1.1(0x1408fd08)
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/runtime.go:2026 +0x6c
panic(0xef9be0, 0x1a7fc60)
        runtime/panic.go:969 +0x153
github.com/dop251/goja.(*vm).try.func1(0x1436b480, 0x0, 0x1408fc70, 0x0, 0x0, 0x0, 0x1408fcb0)
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/vm.go:406 +0x489
panic(0xef9be0, 0x1a7fc60)
        runtime/panic.go:969 +0x153
runtime/internal/atomic.Xadd64(0x15782dcc, 0x1, 0x0, 0x1, 0x1)
        runtime/internal/atomic/asm_386.s:105 +0xc
github.com/loadimpact/k6/js/modules/k6.(*K6).Check(0x1aa7350, 0x122c620, 0x134b8a40, 0x1236ae0, 0x1520aa40, 0x1236ae0, 0x1520b360, 0x0, 0x0, 0x0, ...)
        github.com/loadimpact/k6/js/modules/k6/k6.go:174 +0x411
reflect.Value.call(0xf5ee60, 0x1aa7350, 0x213, 0x100e7bc, 0x9, 0x15782d80, 0x4, 0x4, 0x138ac460, 0x4e812a, ...)
        reflect/value.go:476 +0x6ed
reflect.Value.CallSlice(0xf5ee60, 0x1aa7350, 0x213, 0x15782d80, 0x4, 0x4, 0x0, 0x1520cc20, 0x55555555)
        reflect/value.go:350 +0x7a
github.com/loadimpact/k6/js/common.Bind.func1(0x1237020, 0x1aa71a0, 0x157694c0, 0x2, 0x8, 0x1520ce10, 0xf1000001)
        github.com/loadimpact/k6/js/common/bridge.go:241 +0x639
github.com/dop251/goja.(*vm)._nativeCall(0x1436b480, 0x14c86240, 0x2)
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/vm.go:1817 +0x221
github.com/dop251/goja.call.exec(0x2, 0x1436b480)
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/vm.go:1789 +0x8bd
github.com/dop251/goja.(*vm).run(0x1436b480)
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/vm.go:307 +0x83
github.com/dop251/goja.(*funcObject).call(0x157685b0, 0x1237020, 0x1aa71a0, 0x151f9650, 0x1, 0x1, 0x0, 0x0, 0x4, 0x429392)
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/func.go:161 +0x301
github.com/dop251/goja.(*funcObject).Call(...)
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/func.go:129
github.com/dop251/goja.AssertFunction.func1.2()
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/runtime.go:2031 +0x64
github.com/dop251/goja.(*vm).try(0x1436b480, 0x1408fcc0, 0x0)
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/vm.go:412 +0xdc
github.com/dop251/goja.AssertFunction.func1(0x1237020, 0x1aa71a0, 0x151f9650, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        github.com/dop251/goja@v0.0.0-20210216182323-60bc6ebb9fc1/runtime.go:2030 +0xd2
github.com/loadimpact/k6/js.(*VU).runFn(0x146f1680, 0x122c620, 0x134b8a40, 0x1, 0x138eaa20, 0x151f9650, 0x1, 0x1, 0x0, 0x0, ...)
        github.com/loadimpact/k6/js/runner.go:711 +0x19a
github.com/loadimpact/k6/js.(*ActiveVU).RunOnce(0x138ebf00, 0x0, 0x0)
        github.com/loadimpact/k6/js/runner.go:659 +0x1bf
github.com/loadimpact/k6/lib/executor.getIterationRunner.func1(0x122c600, 0x14c99640, 0x1220af0, 0x138ebf00, 0x151f95f8)
        github.com/loadimpact/k6/lib/executor/helpers.go:86 +0x44
github.com/loadimpact/k6/lib/executor.PerVUIterations.Run.func3(0x12271d0, 0x146f1680)
        github.com/loadimpact/k6/lib/executor/per_vu_iterations.go:231 +0x1c1
created by github.com/loadimpact/k6/lib/executor.PerVUIterations.Run
        github.com/loadimpact/k6/lib/executor/per_vu_iterations.go:244 +0xa0e

Goja stack:
file:///.../scripts/check.js:9:92(42)
ERRO[0000] a panic occurred in VU code but was caught: runtime error: invalid memory address or nil pointer dereference  executor=per-vu-iterations scenario=default

running (00m00.5s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [========================] 1 VUs  00m00.5s/10m0s  1/1 iters, 1 per VU

     ✓ is status 200

     http_req_blocked...............: avg=279.06ms min=279.06ms med=279.06ms max=279.06ms p(90)=279.06ms p(95)=279.06ms
     http_req_connecting............: avg=275.06ms min=275.06ms med=275.06ms max=275.06ms p(90)=275.06ms p(95)=275.06ms
     http_req_duration..............: avg=233.97ms min=233.97ms med=233.97ms max=233.97ms p(90)=233.97ms p(95)=233.97ms
       { expected_response:true }...: avg=233.97ms min=233.97ms med=233.97ms max=233.97ms p(90)=233.97ms p(95)=233.97ms
     http_req_failed................: 0.00% ✓ 0 ✗ 1
     http_req_receiving.............: avg=0s       min=0s       med=0s       max=0s       p(90)=0s       p(95)=0s
     http_req_sending...............: avg=0s       min=0s       med=0s       max=0s       p(90)=0s       p(95)=0s
     http_req_tls_handshaking.......: avg=0s       min=0s       med=0s       max=0s       p(90)=0s       p(95)=0s
     http_req_waiting...............: avg=233.97ms min=233.97ms med=233.97ms max=233.97ms p(90)=233.97ms p(95)=233.97ms
```

**Comment by MStoykov** [comment]
Hi @shongcheng, 

You are running a 32-bit version of k6, which looks to be hitting a limitation in ... 32bit hardware and golang explained in this [blog post](https://www.programmersought.com/article/69621805140/) and a really old issue which boils down to [this comment](https://github.com/golang/go/issues/5278#issuecomment-66078007). 

While we could and likely will fix it through aligning some fields, it seems that nobody is testing or using the 32 bit of k6 and it also has other failing tests, most of which we will probably not try to fix. 

Also given the age of 32 bit software I guess you are using the 32bit version *by mistake* not because you actually have 32bit hardware? 

Given all the above we are likely to:
1. drop 32bit builds of k6 for v0.32.0  and forward
2. align the fields Passes and Fails of the [Check struct](https://github.com/k6io/k6/blob/master/lib/models.go#L188-L208)

While for you this is not present on 64bit builds of k6 which you can get from https://github.com/k6io/k6/releases/download/v0.31.1/k6-v0.31.1-win64.msi

**Comment by shongcheng** [comment]
Works with the 64-bit version.

Thank you.



Regards, Shong Cheng.

________________________________
